name: staffportal
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  provider: ^6.1.5+1
  another_flushbar: ^1.12.32
  shared_preferences: ^2.5.4
  shaky_animated_listview: ^0.0.5
  search_choices: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/languages/en.json
    - assets/languages/sw.json
