// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHYo0X25Z5YlcMrtl6TYej0c3B4nbta-8',
    appId: '1:949962534962:android:e8f4464309f0ab1d244c2b',
    messagingSenderId: '949962534962',
    projectId: 'hrh-znz',
    storageBucket: 'hrh-znz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhg5CrMXjcnGPMAhw9_lYYwaxAZqtJqc0',
    appId: '1:949962534962:ios:6e843a6a5fa1aa74244c2b',
    messagingSenderId: '949962534962',
    projectId: 'hrh-znz',
    storageBucket: 'hrh-znz.firebasestorage.app',
    iosBundleId: 'com.hrhs.mhz',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD782AjJ1bdIDSiDQTZBUp0uiiqY1NnXug',
    appId: '1:949962534962:web:3c7660f21d62de2e244c2b',
    messagingSenderId: '949962534962',
    projectId: 'hrh-znz',
    authDomain: 'hrh-znz.firebaseapp.com',
    storageBucket: 'hrh-znz.firebasestorage.app',
    measurementId: 'G-4EX2R2M47T',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhg5CrMXjcnGPMAhw9_lYYwaxAZqtJqc0',
    appId: '1:949962534962:ios:6e843a6a5fa1aa74244c2b',
    messagingSenderId: '949962534962',
    projectId: 'hrh-znz',
    storageBucket: 'hrh-znz.firebasestorage.app',
    iosBundleId: 'com.hrhs.mhz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD782AjJ1bdIDSiDQTZBUp0uiiqY1NnXug',
    appId: '1:949962534962:web:04098fc1f7946116244c2b',
    messagingSenderId: '949962534962',
    projectId: 'hrh-znz',
    authDomain: 'hrh-znz.firebaseapp.com',
    storageBucket: 'hrh-znz.firebasestorage.app',
    measurementId: 'G-QLGEVSK1TN',
  );

}